### ISSUE TITLE
No smooth video when using simple-whip-client and Millicast 

### ISSUE THREAD

**Issue by jdvconsult** [meetecho/simple-whip-client#12]
Hi

We tried to publish an RTSP stream using the simple-whip-client towards Millicast.
It works, at least it publishes video to Millicast, but the playback is not smooth, a lot of framedrops, no smooth image, ...
When trying the 'old' method, publishing using RMTP, playback is smooth (given the 3sec delay).

WHIP command:
```
docker run -it --rm -e "U=https://director.millicast.com/api/whip/STREAM" -e "T=TOKEN" -e "V=rtspsrc location=rtsp://192.168.30.3/Streaming/Channels/1 latency=0 name=rtsp ! rtph264depay ! rtph264pay config-interval=-1 ! application/x-rtp,media=video,encoding-name=H264" simple-whip-client
```
I ran the simple-whip-client on both RPI4 and on a X86 Mac OS, both using docker.
The DockerFile entrypoint was changed a bit to be able to pass the TOKEN
```
ENV U=http://localhost:3000/whip/foo
ENV T=
ENV A="audiotestsrc is-live=true wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay pt=100 ssrc=1 ! queue ! application/x-rtp,media=audio,encoding-name=OPUS,payload=100"
ENV V="videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay pt=96 ssrc=2 ! queue ! application/x-rtp,media=video,encoding-name=VP8,payload=96"

ENTRYPOINT ./whip-client -l 7 -u $U -t $T -V "$V" -A "$A" -S stun://stun.l.google.com:19302
```

GStreamer command
```
gst-launch-1.0 \
rtspsrc location=rtsp://192.168.30.3/Streaming/Channels/1 latency=0 ! rtph264depay  ! flvmux name=mux ! queue ! rtmpsink location="rtmp://live-rtmp-pub.millicast.com:1935/v2/pub/STREAM?token=TOKEN live=1" 
```

**Comment by lminiero** [comment]
This may be an issue with the pipeline you're trying to create, so I'd ask on a GStreamer mailing list, not here, as I'm not that familiar with what may go wrong there. One thing I'd investigate is how you configure `vp8enc`, since IIRC the default behaviour uses more CPU and so may be more inefficient: you probably have to add some attributres to tweak how the encoder is created. You're not providing a target bitrate either, and I'm not sure what the default behaviour is in that case: if it's generating a bitrate higher than the available bandwidth, that will cause losses too.

**Comment by lminiero** [comment]
Closing for lack of feedback.
